# Generated by Django 4.2.30 on 2026-04-25 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('total_break_minutes', models.IntegerField(default=0)),
                ('worked_minutes', models.IntegerField(default=0)),
                ('overtime_minutes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Session',
                'verbose_name_plural': 'Work Sessions',
                'db_table': 'work_sessions',
                'ordering': ['-date', '-clock_in'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BreakSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='timesheet.worksession')),
            ],
            options={
                'verbose_name': 'Break Session',
                'verbose_name_plural': 'Break Sessions',
                'db_table': 'break_sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
