# Generated by Django 4.2.30 on 2026-04-25 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_task_estimated_hours_project_task_project'),
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='category',
            field=models.CharField(choices=[('HR', 'HR'), ('TECHNICAL', 'Technical'), ('PAYROLL', 'Payroll'), ('LEAVE', 'Leave'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='tasks.task'),
        ),
    ]
